services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    # auto-register all commands as services
    Pimcore\Bundle\ImageTaggingBundle\Command\:
        resource: '../../Command'


    # auto-register all controllers as services
    Pimcore\Bundle\ImageTaggingBundle\Controller\:
        resource: '../../Controller'

    Pimcore\Bundle\ImageTaggingBundle\Service\ImageTaggingService: ~